<?php

/**
 * @file
 * Contains newyork1_aboutus.module..
 */

/**
 * Implements hook_help().
 */
function newyork1_aboutus_theme($existing, $type, $theme, $path) {
  return [
    'newyork1_aboutus' => [
      'variables' => [
        'apple' => NULL,
        'orgName' => NULL,
      ],
    ],
    'newyork1_aboutleadership' => [
      'variables' => [
        'apple' => NULL,
        'orgName' => NULL,
      ],
    ],
  ];
}
