<?php

/**
 * @file
 * Contains qbpl_volunteer.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qbpl_volunteer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qbpl_volunteer module.
    case 'help.page.qbpl_volunteer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Volunteer with Queens Library') . '</p>';
      return $output;

    default:
  }
}
